version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - .postgres/data:/var/lib/postgresql/data
    networks:
      - app-network

  nestjs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    networks:
      - app-network
  
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge